<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title><?=$page_titel?></title>
</head>
<body>
    <?php if(isset($_SESSION['username'])):?>
    <div class="container p-3 mb-3 border-bottom">
      <div class="align-items-center justify-content-center ">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center ">
          <li><a href="/" class="nav-link px-2 link-secondary">todos</a></li>
          <li><a href="#" class="nav-link px-2 link-dark">about</a></li>
        </ul>
        <div  class="dropdown d-flex justify-content-center mt-2">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="50" height="50" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item"><?=$_SESSION['username'];?></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">New project</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="log_out.php">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
    <?php endif;?>
    <div class="container">
        <?php include $template.".phtml"; ?>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>