
  <div class="row ms-5 mt-5">
    <div class="col">
        <h3>details de <?= $todo['titel']; ?></h3>
    </div>
    <div class="col">
        <a href="./index.php" class="btn btn-primary"><i class="bi bi-house"></i></a>
    </div>
  </div>
<div class="card mt-2" style="width:50rem;">
    <div class="card-body">
    <h5 class="card-title">
        <p><strong>Titre</strong></p>
        <p class="card-text"><?= $todo['titel'];?></p>
    </h5>
    <h6 class="card-titel mb-2  pt-1">description</h6>
    <p class="card-text"><?= $todo['description'];?></p>
    <h5 class="card-title">
        <p><strong>status :</strong><?=$todo['complete']?'complete':'incomplete' ?></p>
    </h5>
    <h5 class="card-title">
        <p><strong>Date :</strong><?=$todo['due_date'] ?></p>
    </h5>
  </div>

    <a href="update.php?id=<?=$todo['id']?>" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
    <button class="btn btn-danger"  data-bs-toggle="modal"  data-bs-target="#deletetodo<?=$todo['id']?>"><i class="bi bi-trash3"></i></button>  
            <div class="modal fade" id="deletetodo<?=$todo['id']?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><?= $todo['id']?></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <?=$todo['titel']?>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a href="delete.php?id=<?=$todo['id']?>" type="button" class="btn btn-danger">delete</a>
          </div>
        </div>
      </div>
    </div>
</div>