  
  <div class="contianer d-flex justify-content-center m-4">
  <form class="shadow rounded m-4 p-4 w-50" action="<?= $_SERVER['PHP_SELF'] ?>" method="POST" enctype="multipart/form-data">
  <?php if(!empty($errors)): ?>
  <div class="alert alert-danger" role="alert">
       <?= $errors[0] ;?>
    </div>
<?php endif;?>
  <h1 class=" mb-4 fw-normal text-center"> Sign Up</h1>
  <div class="form-floating">
      <input type="text" name="username"  class="form-control mb-3"  id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">user name</label>
    </div>
    <div class="form-floating">
      <input type="text" name="email"  class="form-control mb-3"  id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" name="password" class="form-control mb-3" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>
    <div class="form-floating">
      <input type="password" name="confirm" class="form-control mb-3" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Confirme Password</label>
    </div>
    <div class="form-floating">
      <input type="file" name="avatar" class="form-control mb-3" id="floatingPassword" placeholder="file">
      <label for="floatingPassword">Avatar</label>
    </div>
    <button style="margin-left:240px;padding:10px 25px;" class="btn btn-outline-primary " name="signup" type="submit">Sign in</button>
     <p class="text-center mt-2">I have an aucount <a class="text-decoration-none " href="login.php">Log in  Here </a></p>
    <p class="mt-4 mb-3 text-muted text-center">&copy;lbezz 2022-2023</p>
  </form>
  </div>